name: configuring backend server
hosts: backend.guru97s.cloud
become: yes
vars:
  login_host: db.guru97s.cloud
  mysql_root_password: "ExpenseApp@1"
tasks:
  - name: disable nodejs
    ansible.builtin.command: dnf module disable nodejs -y
  - name: enabling nodejs:20 version
    ansible.builtin.command: dnf module enable nodjes:20 -y
  - name: installing nodejs
    ansible.builtin.dnf:
      name: "{{item}}"
      state: installed
    loop: 
      - nodejs
      - mysql
  - name: adding user expense
    ansible.builtin.user:
      name: expense
  - name: creating app directory
    ansible.built.file:
      path: /app
      state: directory
